name: mpi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.24.4
  - scipy=1.10.1
  - pandas=2.0.3
  - matplotlib=3.7.3
  - tqdm=4.65.0
  - pytorch=2.0.1
  - scikit-learn=1.3.2
  - h5py=3.11.0
  - pip:
      - mujoco==3.1.6
      - gym==0.23.1
      - mujoco-py==2.1.2.14
      - transformers==4.46.3
      - minari==0.5.2
      - gymnasium-robotics>=1.2.4
      - wandb

