path:
  checkpoint_path: results/checkpoints
  weights_path: results/weights
  logs_path: results/logs
  videos_path: results/videos
  experiment_name: LPT_kitchen


BasicLPT:
  state_dim: 59 
  act_dim: 9 
  context_len: 15 
  h_dim: 16 
  n_blocks: 3 
  n_heads: 1 
  drop_p: 0.1 
  n_latent: 4
  device: cuda
  reward_weight: 1.0
  action_weight: 1.0
  z_n_iters: 10
  langevin_step_size: 0.3
  noise_factor: 0.1


BasicDT:
  h_dim: 16
  context_len: 15
  state_dim: 59
  act_dim: 9
  n_heads: 1
  n_blocks: 3
  drop_p: 0.1


training:
  batch_size: 64
  learning_rate: 1e-4
  weight_decay: 0.01
  epochs: 2
  grad_clip: 1.0
  logger: ["tensorboard","file","wandb"]
  debug: false
  device: cuda
  shuffle: true
  num_workers: 1


environment:
  name: kitchen-mixed-v2 #the name would be used for import, youc ahnge change tt
  env_type: D4RL
  env_provider: minari #the env_type define the provider
  max_episode_steps: 5000
  seed: 42
  context_len: 15


others:
  tensorboard_port: 6006
  logger_level: info




