path:
  checkpoint_path: results/checkpoints
  weights_path: results/weights
  logs_path: results/logs
  videos_path: results/videos
  experiment_name: LPT_halfcheetah


BasicLPT:
  state_dim: 17  # TODO currently we hardcoded this,  is it possible to automatically infer this from data
  act_dim: 6 # TODO same as above 
  context_len: 15
  h_dim: 16 
  n_blocks: 3 
  n_heads: 1 
  drop_p: 0.1 
  n_latent: 4
  # device: mps
  reward_weight: 1.0
  action_weight: 1.0
  z_n_iters: 10
  langevin_step_size: 0.3
  noise_factor: 0.1


BasicDT:
  h_dim: 16
  context_len: 15
  state_dim: 17
  act_dim: 6
  n_heads: 1
  n_blocks: 3
  drop_p: 0.1
  # device: cpu


training:
  batch_size: 64
  learning_rate: 1e-4
  weight_decay: 0.01
  epochs: 2
  grad_clip: 1.0
  logger: ["tensorboard","file","wandb"]
  debug: false
  device: cpu
  shuffle: true
  num_workers: 1


environment:
  name: halfcheetah-expert-v0 #the name would be used for import, youc ahnge change tt
  env_type: D4RL
  env_provider: minari #the env_type define the provider
  max_episode_steps: 5000
  seed: 42
  context_len: 15


others:
  tensorboard_port: 6006
  logger_level: info




