path:
  checkpoint_path: results/checkpoints
  weights_path: results/weights
  logs_path: results/logs
  videos_path: results/videos
  experiment_name: LPT_maze2d


BasicLPT:
  state_dim: 8  
  act_dim: 2
  context_len: 150
  h_dim: 256 
  n_blocks: 4 
  n_heads: 1 
  drop_p: 0.1 
  n_latent: 32
  device: mps
  reward_weight: 1.0
  action_weight: 1.0
  z_n_iters: 20
  langevin_step_size: 0.3
  noise_factor: 0.1


BasicDT:
  h_dim: 16
  context_len: 15
  state_dim: 17
  act_dim: 6
  n_heads: 1
  n_blocks: 3
  drop_p: 0.1


training:
  batch_size: 128
  learning_rate: 3e-5
  weight_decay: 0.01
  epochs: 4
  grad_clip: 1.0
  logger: ["file","tensorboard"]
  debug: false
  device: mps
  shuffle: true
  num_workers: 1


environment:
  name: maze2d-umaze-v2 #the name would be used for import, youc ahnge change tt
  env_type: D4RL
  env_provider: minari #the env_type define the provider
  max_episode_steps: 5000
  seed: 42
  context_len: 150


others:
  tensorboard_port: 6006
  logger_level: info




